const endpoints = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    forgetPassword: "/auth/forgetPassword",
    refresh: "/auth/refresh",
  },
  user: {
    create: "/users",
    delete: (id) => `/users/${id}`,
    profile: "/users/profile",
    update: (id) => `/users/${id}`,
    changePass: (id) => `/users/changePass/${id}`,
    sendSms: (id) => `/users/sms/${id}`,
    setLocation: "/users/location/",
    listAll: "/users/",
  },
  proforma: {
    listAll: "/proforma/user/my",
    getApprovedFile: (id) => `/proforma/file/${id}`,
    convert: (id) => `/proforma/convert/${id}`,
    listByToken: (token) => `/proforma/token/${token}`,
    updateProformCustomerFile: (token) => `/proforma/token/${token}`,
    generateNewToken: (id) => `/proforma/generateNewToken/${id}`,
    update: (id) => `/proforma/${id}`,
    listOne: (id) => `/proforma/${id}`,
    detail: (id) => `/proforma/${id}`,
    create: "/proforma/",
    delete: (id) => `/proforma/${id}`,
    setProformaIsSent: (id) => `/proforma/sent/${id}`,
  },
  invoice: {
    listAll: "/invoice/user/my",
    update: (id) => `/invoice/${id}`,
    listOne: (id) => `/invoice/${id}`,
    detail: (id) => `/invoice/${id}`,
    create: "/invoice/",
    delete: (id) => `/invoice/${id}`,
  },
  customer: {
    listAll: "/customer/",
    update: (id) => `/customer/${id}`,
    listOne: (id) => `/customer/${id}`,
    detail: (id) => `/customer/${id}`,
    create: "/customer/",
    delete: (id) => `/customer/${id}`,
  },
  notifications: {
    unreadCount: "notifications/unread",
    markAsRead: (id) => `notifications/${id}/read`,
    markAsunread: (id) => `notifications/${id}/unread`,
    listSent: "/notifications/sent",
    listReceived: "/notifications/received",
    listOne: (id) => `/notifications/${id}`,
    create: "/notifications/",
    delete: (id) => `/notifications/${id}`,
    update: (id) => `/notifications/${id}`,
  },
  good: {
    listAll: (page, limit, search) =>
      `/goods?page=${page}&limit=${limit}&search=${search}`,
    listCount: (count) => `/goods/count/${count}`,
    update: (id) => `/goods/${id}`,
    listOne: (id) => `/goods/${id}`,
    detail: (id) => `/goods/${id}`,
    create: "/goods/",
    uploadExcel: "/goods/upload-excel",
    delete: (id) => `/goods/${id}`,
  },
  unit: {
    listAll: "/units/",
    update: (id) => `/units/${id}`,
    listOne: (id) => `/units/${id}`,
    detail: (id) => `/units/${id}`,
    create: "/units/",
    delete: (id) => `/units/${id}`,
  },
  sms: {
    bulk: "https://api.sms.ir/v1/send/bulk",
    verify: "https://api.sms.ir/v1/send/verify",
  },
};

export default endpoints;
